---
# Environment specific values, override helm_deploy/health-kick/values.yaml
generic-service:
  ingress:
    host: health-kick.prison.service.justice.gov.uk
    contextColour: green

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
generic-prometheus-alerts:
  alertSeverity: hmpps_tech
  ingressAlertsEnabled: false
